matrice: matrice.o generateur.o main.o
	g++ -o matrice matrice.o generateur.o main.o
matrice.o: matrice.cpp
	g++ -o matrice.o -c matrice.cpp
generateur.o: generateur.cpp
	g++ -o generateur.o -c generateur.cpp
main.o: main.cpp
	g++ -o main.o -c main.cpp
